In [4]:
import numpy as np

In [5]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [7]:
%timeit [j**4 for j in range(1,9)]

3.34 µs ± 309 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
%timeit np.arrange(1,9)**4

NameError: name 'np' is not defined

# Array

In [10]:
import numpy as np

In [15]:
x=[1,2,3,4]

y=np.array(x)


print(y)
print(type(y))

print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [14]:
l = []

for i in range(1,5):
    int_1 = int(input("Enter : "))
    l.append(int_1)

print(np.array(l))

Enter : 12
Enter : 24
Enter : 36
Enter : 48
[12 24 36 48]


In [16]:
a = np.array([[1,2,3,4],[1,2,3,4]])

print(a)

print(a.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [18]:
arr = np.array([1,2,3,4],ndmin = 10)

print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [4]:
import numpy as np

arr_zero = np.zeros(4)

arr_zero1 = np.zeros((3,4))

print(arr_zero)

print()

print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [5]:
import numpy as np
arr_one = np.ones(4)

print(arr_one)

[1. 1. 1. 1.]


# Empty

In [3]:
import numpy as np
arr_emp = np.empty(4)

print(arr_emp)

[0. 0. 0. 0.]


# Range

In [28]:
arr_range = np.arange(4)

print(arr_range)

[0 1 2 3]


# Diagonal

In [29]:
arr_dia = np.eye(3)

print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr_dia = np.eye(3,5)

print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linespace

In [34]:
arr_line = np.linspace(1,20,num=5)

print(arr_line)

[ 1.    5.75 10.5  15.25 20.  ]


# Random

# rand()

In [4]:
import numpy as np

var =np.random.rand(4)

print(var)

[0.79363885 0.9207346  0.55037903 0.98859979]


In [5]:
var1 = np.random.rand(2,5)

print(var1)

[[0.92519317 0.85928559 0.59984506 0.85818663 0.00112431]
 [0.962465   0.44405179 0.03467945 0.7143818  0.02245074]]


# randn()

In [1]:
#generates numbers according to normal distribution

var2 = np.random.randn(5)

print(var2)

NameError: name 'np' is not defined

# ranf()

In [9]:
#generates numbers according to uniform distribution

var3 = np.random.ranf(5)

print(var3)

[0.78883833 0.71095126 0.44927819 0.7692841  0.57261563]


In [17]:
var4 = np.random.randint(5,20,5)

print(var4)

[18  8 19 18 14]



# Data Type

In [15]:
var = np.array([1,2,3,4])

print("Data Type : ",var.dtype)

Data Type :  int32


In [16]:
var = np.array([12,2.5,3.4])

print("Data Type : ",var.dtype)

Data Type :  float64


In [23]:
x=np.array([1,2,3,4],dtype = np.float64)

print("Data Type : ",x.dtype)

print(x)

Data Type :  float64
[1. 2. 3. 4.]


# Arithmatic Operations

In [24]:
var =np.array([1,2,3,4])

varadd =var + 3

print(varadd)

[4 5 6 7]


In [25]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])

varadd =var1 + var2

print(varadd)

[2 4 6 8]


In [26]:
var =np.array([1,2,3,4])

varadd =var - 3

print(varadd)

[-2 -1  0  1]


In [27]:
var =np.array([1,2,3,4])

varadd =var * 3

print(varadd)

[ 3  6  9 12]


In [28]:
var =np.array([1,2,3,4])

varadd =var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [29]:
var =np.array([1,2,3,4])

varadd =var % 3

print(varadd)

[1 2 0 1]


In [33]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])

var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 + var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [44]:
var = np.array([1,2,3,7,4,5,6,7])

print("min : ",np.min(var))

print("max : ",np.max(var))

print("min : ",np.argmin(var))

print("max : ",np.argmax(var))

print("square root : ",np.sqrt(var))

min :  1
max :  7
min :  0
max :  3
square root :  [1.         1.41421356 1.73205081 2.64575131 2.         2.23606798
 2.44948974 2.64575131]


In [43]:
var1 = np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis=1))

[1 5]


In [46]:
var1 = np.array([1,2,3,4,5])

print(np.sin(var1))

print(np.cos(var1))

print(np.cumsum(var1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1  3  6 10 15]


# Shape

In [1]:
import numpy as np

In [2]:
var =np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [7]:
var1 =np.array([1,2,3,4],ndmin=4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape

In [8]:
var2 = np.array([1,2,3,4,5,6])

print(var2)

print(var2.ndim)

print()

x = var2.reshape(3,2)

print(x)

print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [10]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var3)

print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)

print(x1)

print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [11]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var3)

print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)

print(x1)

print(x1.ndim)

print()

one = x1.reshape(-1)

print(one)

print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Broadcasting

In [12]:
import numpy as np

In [14]:
var1= np.array([1,2,3])

print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()

print(var1+var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
x = np.array([[1],[2]])
print(x.shape)

y =np.array([[1,2,3],[1,2,3]])
print(y.shape)

print()

print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing

In [17]:
var = np.array([1,2,3,4,5])


# Slicing

# Iteartion

In [18]:
var = np.array([9,8,7,6,5,4])

print(var)
print()

for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [20]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1:
    print(j)
    
print()

for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [22]:
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var2)
print()
print(var3.ndim)
print()

for i in np.nditer(var2):
    print(i)

[[1 2 3 4]
 [1 2 3 4]]

1

1
2
3
4
1
2
3
4


In [23]:
var3 = np.array([[1,2,3,4],[1,2,3,4]])
print(var3)
print()
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)

[[1 2 3 4]
 [1 2 3 4]]

2

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 1
(1, 1) 2
(1, 2) 3
(1, 3) 4


# Copy vs View

In [28]:
var = np.array([1,2,3,4])

co = var.copy()

var[1]=40

print("var : ", var)

print("copy :",co)

var :  [ 1 40  3  4]
copy : [1 2 3 4]


In [29]:
var = np.array([9,8,7,6])

vi = var.view()

var[1]=80

print("var : ", var)

print("copy :",vi)

var :  [ 9 80  7  6]
copy : [ 9 80  7  6]


# Join Array

In [33]:
var1 = np.array([1,2,3,4])

var2 = np.array([9,8,7,6])

ar = np.concatenate((var1,var2))

print(ar)

[1 2 3 4 9 8 7 6]


In [35]:
var1 = np.array([[1,2],[3,4]])

var2 = np.array([[9,8],[7,6]])

ar = np.concatenate((var1,var2),axis=1)


print(ar)

[[1 2 9 8]
 [3 4 7 6]]


In [4]:
import numpy as np

var1 = np.array([1,2,3,4])

var2 = np.array([9,8,7,6])

ar = np.stack((var1,var2),axis=1)

ar_1 = np.hstack((var1,var2))      #row

ar_2 = np.vstack((var1,var2))      #column

ar_3 = np.dstack((var1,var2))      #height

print(ar)
print()
print(ar_1)
print()
print(ar_2)
print()
print(ar_3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array

In [5]:
import numpy as np

In [9]:
var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print()
print(ar)
print()
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]


# Search

In [10]:
import numpy as np

In [11]:
var = np.array([1,2,3,4,2,5,2,5,6,7])

x = np.where(var == 2)

print(x)

(array([1, 4, 6], dtype=int64),)


In [13]:
var1 = np.array([1,2,3,4,6,7,8])

x1 = np.searchsorted(var1 ,5)

print(x1)

4


# Sort

In [14]:
var = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var))

[ 1  2  3  4  5  6  7 12 22 52]


# Filter Array

In [17]:
var = np.array([4,2,3,1])

f = [True,False,False,True]

a = var[f]

print(a)

print(type(a))

[4 1]
<class 'numpy.ndarray'>


# Shuffle

In [19]:
var = np.array([4,2,3,1.5])

np.random.shuffle(var)

print(var)

[1.5 3.  2.  4. ]


# Unique

In [21]:
var = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var,return_index=True,return_counts=True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64), array([1, 4, 1, 1, 1, 1, 1], dtype=int64))


# Resize

In [22]:
var1 = np.array([1,2,3,4,5,6])

y= np.resize(var1,(2,3))

print(y)

[[1 2 3]
 [4 5 6]]


# Flatten

In [23]:
var1 = np.array([1,2,3,4,5,6])

y= np.resize(var1,(2,3))

print(y)
print()

print("Flatten : ",y.flatten(order="F"))

[[1 2 3]
 [4 5 6]]

Flatten [1 4 2 5 3 6]


# Ravel

In [24]:
var1 = np.array([1,2,3,4,5,6])

y= np.resize(var1,(2,3))

print(y)
print()

print("Ravel : ",y.ravel(order="K"))

[[1 2 3]
 [4 5 6]]

Ravel :  [1 2 3 4 5 6]


# Insert

In [26]:
var = np.array([1,2,3,4,5,6])

print(var)

v = np.insert(var,2,40)
print(v)

[1 2 3 4 5 6]
[ 1  2 40  3  4  5  6]


In [27]:
var1 = np.array([[1,2,3],[4,5,6]])

v1 = np.insert(var1,2,40,axis = 1)

print(v1)

[[ 1  2 40  3]
 [ 4  5 40  6]]


In [29]:
var = np.array([1,2,3,4,5,6])

print(var)

x = np.append(var,40)

print(x)

[1 2 3 4 5 6]
[ 1  2  3  4  5  6 40]


# Delete

In [30]:
var = np.array([1,2,3,4,5,6])

print(var)

d = np.delete(var,2)

print(d)

[1 2 3 4 5 6]
[1 2 4 5 6]


# Matrix

In [32]:
import numpy as np

In [34]:
var1 = np.matrix([[1,2,3],[1,2,3]])

print(var1)

print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [35]:
var2 = np.matrix([[1,2,3],[1,2,3]])

print(var2)

print(type(var2))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [36]:
var3 = np.matrix([[1,2,3],[1,2,3]])
var4 = np.matrix([[1,2,3],[1,2,3]])


print(var3+var4)

[[2 4 6]
 [2 4 6]]


In [38]:
var5 = np.matrix([[1,2],[1,2]])
var6 = np.matrix([[1,2],[1,2]])

print(var5*var6)
print()
print(var5.dot(var6))

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [41]:
var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print()

print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [42]:
var1 = np.matrix([[1,2],[3,4]])

print(var1)
print()

print(np.linalg.inv(var1))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [44]:
var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()
print(np.linalg.matrix_power(var2,4))

[[1 2]
 [3 4]]

[[199 290]
 [435 634]]


In [45]:
var3 = np.matrix([[1,2],[3,4]])

print(var3)
print()
print(np.linalg.det(var3))

[[1 2]
 [3 4]]

-2.0000000000000004
