In [1]:
import numpy as np

# ndarray

In [4]:
a=np.array([1,2,3])
print(a)

print(a[0])
print(a[2])

[1 2 3]
1
3


In [6]:
#Benifits of Numpy array
# 1)Less memory
# 2)Fast
# 3)Convinient

In [9]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# Basic Array Operations

In [12]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [15]:
a=np.array([[1,2],[3,4],[5,6]])
a.itemsize

#It prints the byte size

4

In [16]:
a.dtype

dtype('int32')

In [19]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.itemsize
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
a.size

#No of elements in array

6

In [23]:
a.shape

(3, 2)

In [24]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [27]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [28]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape)
a.reshape(2,3)
a

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a.ravel()

#It doesn't touch the original array instead it returns the new array

array([1, 2, 3, 4, 5, 6])

In [37]:
a.min()

1

In [38]:
a.max()

6

In [39]:
a.sum()

21

In [40]:
a.sum(axis=0)

array([ 9, 12])

In [41]:
a.sum(axis=1)

array([ 3,  7, 11])

In [42]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [43]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

a.dot(b)

# This performsmatrix multiplication

array([[19, 22],
       [43, 50]])

# Indexing and Slicing

In [44]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [45]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [46]:
a[1,2]

3

In [47]:
a[0:2,2]

array([8, 3])

In [48]:
a[-1,0:2]

array([9, 3])

In [49]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

# Iterate through array

In [51]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])

for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [52]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


# Sticking Two arrays

In [53]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [54]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [56]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [57]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [58]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [60]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [61]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [64]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [66]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [69]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [70]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11
